name: market-daily
on:
  schedule:
    - cron: "35 * * * *"   # Run at :35 every hour (UTC); script posts only at 16:35 Tallinn
  workflow_dispatch: {}     # Allows manual runs from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install yfinance requests pytz pandas numpy

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python market_daily.py
